language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y unoconv"

install: "composer install"

script: "./vendor/bin/robo test"

cache:
  apt: true